sjs.using("Core5.Widget.Form")
.using("Core5.Layout.Form")
.using("Common.InputFlow")
.using("Core5.Bind.BindTarget")
.define(function(form,formLayout,inputFlow,bindTarget){
    return {
        $extend:form
        ,$mixin:[formLayout]
        ,inner:[
            {
                prompt:"other"
                ,fieldNo:"aaa"
            }
            ,{
                prompt:"other2"
                ,fieldNo:"bbb"
            }
            ,{
                prompt:"Manager Flow"
                ,colspan:2
                ,noTdTag:true
                ,$extend:inputFlow
                ,$mixin:[bindTarget]
                ,fieldNo:"MANAGERS"
                ,"@text":"item.MANAGERS_NAME"
            }
            ,{
                type:"button"
                ,text:"test"
                ,evt:'test'
                ,colspan:2
            }
        ]
        ,onTest:function(){
            alert(JsonHelper.encode(this.item));
        }
    };
});